sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sihannilam/portfolio .

script:
  - docker run -e CI=true sihannilam/portfolio npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-415067012983"
  bucker_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
